/**
 * AURAWORLD — the gallery. Conductor-owned; builders do not edit this file.
 * Six hero sims, one register. Black ground, white Helvetica, one signal colour.
 */
import { SCENES, ROSTER } from "../scenes/registry";
import { C, TYPE } from "../design/system";

const lbl: React.CSSProperties = {
  fontFamily: TYPE.family,
  fontSize: TYPE.micro,
  fontWeight: TYPE.weightLabel,
  letterSpacing: TYPE.tracking,
  textTransform: "uppercase",
  margin: 0,
};

export function Gallery() {
  return (
    <div style={{ height: "100vh", overflowY: "auto", background: C.ink, color: C.bone }}>
      <div style={{ maxWidth: 1180, margin: "0 auto", padding: "72px 40px 120px" }}>
        <p style={{ ...lbl, color: C.signal }}>AURAWORLD — REALITY COMPILER LAB</p>
        <h1
          style={{
            fontFamily: TYPE.family,
            fontWeight: 700,
            fontSize: "clamp(30px,4.4vw,58px)",
            lineHeight: 1.02,
            letterSpacing: "-0.02em",
            margin: "22px 0 0",
            maxWidth: 900,
          }}
        >
          The world does not act on data.
          <br />
          It acts on compiled realities.
        </h1>
        <p
          style={{
            fontFamily: TYPE.family,
            fontSize: 14,
            lineHeight: 1.55,
            opacity: 0.5,
            maxWidth: 620,
            marginTop: 22,
          }}
        >
          Six instruments. Each holds one world constant, turns exactly one hidden control
          surface, and measures how far the resulting futures drift apart.
        </p>

        <div
          style={{
            marginTop: 64,
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(330px, 1fr))",
            gap: 1,
            background: C.hair,
            border: `1px solid ${C.hair}`,
          }}
        >
          {ROSTER.map((r, i) => {
            const built = SCENES.find((s) => s.code === r.code);
            return (
              <a
                key={r.code}
                href={built ? `/?scene=${r.code}` : undefined}
                style={{
                  background: C.ink,
                  padding: "26px 24px 30px",
                  textDecoration: "none",
                  display: "block",
                  minHeight: 190,
                  cursor: built ? "pointer" : "default",
                  opacity: built ? 1 : 0.32,
                }}
              >
                <div style={{ display: "flex", justifyContent: "space-between" }}>
                  <p style={{ ...lbl, opacity: 0.4 }}>{String(i + 1).padStart(2, "0")}</p>
                  <p style={{ ...lbl, color: built ? C.signal : C.dim }}>
                    {built ? "READY" : "PENDING"}
                  </p>
                </div>
                <p
                  style={{
                    fontFamily: TYPE.family,
                    fontSize: 21,
                    fontWeight: 700,
                    letterSpacing: "-0.01em",
                    margin: "16px 0 0",
                  }}
                >
                  {r.title}
                </p>
                <p style={{ ...lbl, opacity: 0.45, marginTop: 10 }}>SURFACE — {r.surface}</p>
                {built && (
                  <p
                    style={{
                      fontFamily: TYPE.family,
                      fontSize: 12.5,
                      lineHeight: 1.5,
                      opacity: 0.5,
                      marginTop: 14,
                    }}
                  >
                    {built.question}
                  </p>
                )}
              </a>
            );
          })}
        </div>

        <p style={{ ...lbl, opacity: 0.28, marginTop: 40 }}>
          {SCENES.length} / {ROSTER.length} BUILT — SOURCE: DEEP-RESEARCH-REPORT-5.MD
        </p>
      </div>
    </div>
  );
}
